blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class BlogPost(models.Model):
	title = models.CharField(max_length=200)
	post = models.TextField()
	date = models.DateField()

	def __str__(self):
		return self.title

project/models.py
from django.db import models

class Project(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	cover = models.ImageField(upload_to='project/images/')
	url = models.URLField(blank=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost

def all_blogs(request):
	blogposts = BlogPost.objects.order_by('-date')
	return render(request, 'blog/all_blogs.html', {'blogs': blogposts, 
		'latestid': len(blogposts), 'titlepage': 'All Blogs'})

def detail(request, blog_id):
	blog = get_object_or_404(BlogPost, pk=blog_id)
	return render(request, 'blog/detail.html', {'blog': blog, 'id': blog_id,
		'blognum': blog_id})

project/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def home(request):
	projects = Project.objects.all()
	return render(request, 'project/home.html', {'projects':projects, 'titlepage': 'Home'})

blog/templates/blog/all_blogs.html
{% extends 'project/base.html' %}
{% load static %}

{% block content %}
<head>
  <title>{{titlepage}} | Django</title>
</head>

<div class="jumbotron text-center" style="background: url({% static 'project/a.png' %})">
  <h1 class="text-secondary">Blog</h1>
  <p class="text-secondary">Bob has written {{ latestid }} blog{{ latestid|pluralize }}</p> 
</div>

<div class="container">
  <div class="row">
    {% for blog in blogs %}
    <div class="col-sm-6">    
      <a href="{% url 'blog:detail' blog.id %}"><h3>{{blog.title}}</h3></a>
      <h6>{{ blog.date|date:'M d Y' }}</h6>
      <p>{{ blog.post|striptags|truncatechars:250 }}</p>
    </div>
    {% endfor %}
  </div>
  <br>
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'project/base.html' %}
{% load static %}

{% block content %}
<head>
	<title>Blog Post {{blognum}} | Django</title>
</head>

<div class="jumbotron text-center" style="background: url({% static 'project/a.png' %})">
  <h1 class="text-secondary">Blog</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12">    
      <h2>{{blog.title}}</h2>
      <h6>{{ blog.date|date:'M d Y' }}</h6>
      <p>{{ blog.post|safe }}</p>
    </div>
  </div>
  <br>
</div>

{% endblock %}

project/templates/project/base.html
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Bob's Portfolio | Django</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:all_blogs' %}">All Blogs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin/">Admin</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

project/templates/project/home.html
{% extends 'project/base.html' %}


{% block content %}

{% load static %}
<head>
	<title>{{titlepage}} | Django</title>
</head>

<div class="jumbotron text-center" style="background: url({% static 'project/a.png' %})">
  <h1 class="text-secondary">Portfolio</h1>
  <p class="text-secondary">Personal page of Bob Owen Villarin</p> 
</div>
 

<div class="container">
  <div class="row">
  	{% for project in projects %}
    <div class="col-sm-4">    
      <h3>{{project.title}}</h3>  
      <img class="img-fluid" src={{project.cover.url}} width=200px>
      <p>{{project.description}}</p>
      <p>
      	{% if project.url %}
      	<a href="{{project.url}}">Link</a>
      	{% endif %}
      </p>
    </div>    
	{% endfor %}
  </div>
</div>

{% endblock %}